// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: backend/v1/types.proto

package backendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Duration      int32                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"` // seconds
	ViewCount     int64                  `protobuf:"varint,6,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	UploadDate    string                 `protobuf:"bytes,7,opt,name=upload_date,json=uploadDate,proto3" json:"upload_date,omitempty"` // YYYYMMDD
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_backend_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Video) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

func (x *Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Subscribers   int64                  `protobuf:"varint,6,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	IsLocal       bool                   `protobuf:"varint,7,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_backend_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Channel) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Channel) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Channel) GetSubscribers() int64 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

func (x *Channel) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

type RawChapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     float64                `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       float64                `protobuf:"fixed64,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawChapter) Reset() {
	*x = RawChapter{}
	mi := &file_backend_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawChapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawChapter) ProtoMessage() {}

func (x *RawChapter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawChapter.ProtoReflect.Descriptor instead.
func (*RawChapter) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *RawChapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RawChapter) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RawChapter) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type VideoDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,3,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Subscribers   int64                  `protobuf:"varint,4,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	Chapters      []*RawChapter          `protobuf:"bytes,5,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoDetails) Reset() {
	*x = VideoDetails{}
	mi := &file_backend_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoDetails) ProtoMessage() {}

func (x *VideoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoDetails.ProtoReflect.Descriptor instead.
func (*VideoDetails) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *VideoDetails) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *VideoDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoDetails) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *VideoDetails) GetSubscribers() int64 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

func (x *VideoDetails) GetChapters() []*RawChapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_backend_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *Link) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	OriginalStart float64                `protobuf:"fixed64,2,opt,name=original_start,json=originalStart,proto3" json:"original_start,omitempty"`
	OriginalEnd   float64                `protobuf:"fixed64,3,opt,name=original_end,json=originalEnd,proto3" json:"original_end,omitempty"`
	AdjustedStart float64                `protobuf:"fixed64,4,opt,name=adjusted_start,json=adjustedStart,proto3" json:"adjusted_start,omitempty"`
	AdjustedEnd   float64                `protobuf:"fixed64,5,opt,name=adjusted_end,json=adjustedEnd,proto3" json:"adjusted_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_backend_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetOriginalStart() float64 {
	if x != nil {
		return x.OriginalStart
	}
	return 0
}

func (x *Chapter) GetOriginalEnd() float64 {
	if x != nil {
		return x.OriginalEnd
	}
	return 0
}

func (x *Chapter) GetAdjustedStart() float64 {
	if x != nil {
		return x.AdjustedStart
	}
	return 0
}

func (x *Chapter) GetAdjustedEnd() float64 {
	if x != nil {
		return x.AdjustedEnd
	}
	return 0
}

type SBSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         float64                `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	End           float64                `protobuf:"fixed64,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SBSegment) Reset() {
	*x = SBSegment{}
	mi := &file_backend_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SBSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SBSegment) ProtoMessage() {}

func (x *SBSegment) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SBSegment.ProtoReflect.Descriptor instead.
func (*SBSegment) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *SBSegment) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SBSegment) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

// CachedDetails carries nullable repeated fields via explicit *_parsed booleans:
// false = never fetched (nil in Go); true = fetched, list may be empty.
type CachedDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Description      string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,2,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Subscribers      int64                  `protobuf:"varint,3,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	Links            []*Link                `protobuf:"bytes,4,rep,name=links,proto3" json:"links,omitempty"`
	LinksParsed      bool                   `protobuf:"varint,5,opt,name=links_parsed,json=linksParsed,proto3" json:"links_parsed,omitempty"`
	Chapters         []*Chapter             `protobuf:"bytes,6,rep,name=chapters,proto3" json:"chapters,omitempty"`
	ChaptersParsed   bool                   `protobuf:"varint,7,opt,name=chapters_parsed,json=chaptersParsed,proto3" json:"chapters_parsed,omitempty"`
	SbSegments       []*SBSegment           `protobuf:"bytes,8,rep,name=sb_segments,json=sbSegments,proto3" json:"sb_segments,omitempty"`
	SbSegmentsParsed bool                   `protobuf:"varint,9,opt,name=sb_segments_parsed,json=sbSegmentsParsed,proto3" json:"sb_segments_parsed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CachedDetails) Reset() {
	*x = CachedDetails{}
	mi := &file_backend_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedDetails) ProtoMessage() {}

func (x *CachedDetails) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedDetails.ProtoReflect.Descriptor instead.
func (*CachedDetails) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *CachedDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CachedDetails) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CachedDetails) GetSubscribers() int64 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

func (x *CachedDetails) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *CachedDetails) GetLinksParsed() bool {
	if x != nil {
		return x.LinksParsed
	}
	return false
}

func (x *CachedDetails) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *CachedDetails) GetChaptersParsed() bool {
	if x != nil {
		return x.ChaptersParsed
	}
	return false
}

func (x *CachedDetails) GetSbSegments() []*SBSegment {
	if x != nil {
		return x.SbSegments
	}
	return nil
}

func (x *CachedDetails) GetSbSegmentsParsed() bool {
	if x != nil {
		return x.SbSegmentsParsed
	}
	return false
}

type LocalVideo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Channel        string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Duration       int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	ViewCount      int64                  `protobuf:"varint,5,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	UploadDate     string                 `protobuf:"bytes,6,opt,name=upload_date,json=uploadDate,proto3" json:"upload_date,omitempty"`
	FilePath       string                 `protobuf:"bytes,7,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	DownloadType   string                 `protobuf:"bytes,8,opt,name=download_type,json=downloadType,proto3" json:"download_type,omitempty"` // "video" | "audio"
	DownloadedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=downloaded_at,json=downloadedAt,proto3" json:"downloaded_at,omitempty"`
	Status         string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // "new" | "started" | "watched"
	LastPlayed     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`
	LastPositionMs int64                  `protobuf:"varint,12,opt,name=last_position_ms,json=lastPositionMs,proto3" json:"last_position_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalVideo) Reset() {
	*x = LocalVideo{}
	mi := &file_backend_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalVideo) ProtoMessage() {}

func (x *LocalVideo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalVideo.ProtoReflect.Descriptor instead.
func (*LocalVideo) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *LocalVideo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalVideo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LocalVideo) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *LocalVideo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *LocalVideo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *LocalVideo) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

func (x *LocalVideo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LocalVideo) GetDownloadType() string {
	if x != nil {
		return x.DownloadType
	}
	return ""
}

func (x *LocalVideo) GetDownloadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DownloadedAt
	}
	return nil
}

func (x *LocalVideo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LocalVideo) GetLastPlayed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPlayed
	}
	return nil
}

func (x *LocalVideo) GetLastPositionMs() int64 {
	if x != nil {
		return x.LastPositionMs
	}
	return 0
}

type YTPlaylist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YTPlaylist) Reset() {
	*x = YTPlaylist{}
	mi := &file_backend_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YTPlaylist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YTPlaylist) ProtoMessage() {}

func (x *YTPlaylist) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YTPlaylist.ProtoReflect.Descriptor instead.
func (*YTPlaylist) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *YTPlaylist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *YTPlaylist) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_backend_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *Playlist) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Playlist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Playlist) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type WatchLaterEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	AddedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchLaterEntry) Reset() {
	*x = WatchLaterEntry{}
	mi := &file_backend_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLaterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLaterEntry) ProtoMessage() {}

func (x *WatchLaterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLaterEntry.ProtoReflect.Descriptor instead.
func (*WatchLaterEntry) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *WatchLaterEntry) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *WatchLaterEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WatchLaterEntry) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *WatchLaterEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WatchLaterEntry) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type HistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	ChannelId     string                 `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	ViewCount     int64                  `protobuf:"varint,7,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	UploadDate    string                 `protobuf:"bytes,8,opt,name=upload_date,json=uploadDate,proto3" json:"upload_date,omitempty"`
	EventType     string                 `protobuf:"bytes,9,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Details       string                 `protobuf:"bytes,10,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	mi := &file_backend_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HistoryEntry) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *HistoryEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HistoryEntry) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *HistoryEntry) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *HistoryEntry) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *HistoryEntry) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *HistoryEntry) GetUploadDate() string {
	if x != nil {
		return x.UploadDate
	}
	return ""
}

func (x *HistoryEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HistoryEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *HistoryEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ActivityEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsLocal         bool                   `protobuf:"varint,3,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	ChannelId       string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName     string                 `protobuf:"bytes,5,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	PlaylistId      string                 `protobuf:"bytes,6,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	PlaylistLocalId int64                  `protobuf:"varint,7,opt,name=playlist_local_id,json=playlistLocalId,proto3" json:"playlist_local_id,omitempty"`
	PlaylistName    string                 `protobuf:"bytes,8,opt,name=playlist_name,json=playlistName,proto3" json:"playlist_name,omitempty"`
	VideoId         string                 `protobuf:"bytes,9,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	VideoTitle      string                 `protobuf:"bytes,10,opt,name=video_title,json=videoTitle,proto3" json:"video_title,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivityEntry) Reset() {
	*x = ActivityEntry{}
	mi := &file_backend_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEntry) ProtoMessage() {}

func (x *ActivityEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEntry.ProtoReflect.Descriptor instead.
func (*ActivityEntry) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *ActivityEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivityEntry) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *ActivityEntry) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ActivityEntry) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ActivityEntry) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *ActivityEntry) GetPlaylistLocalId() int64 {
	if x != nil {
		return x.PlaylistLocalId
	}
	return 0
}

func (x *ActivityEntry) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *ActivityEntry) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *ActivityEntry) GetVideoTitle() string {
	if x != nil {
		return x.VideoTitle
	}
	return ""
}

func (x *ActivityEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DownloadItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Duration      string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	AudioOnly     bool                   `protobuf:"varint,6,opt,name=audio_only,json=audioOnly,proto3" json:"audio_only,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "pending" | "active" | "complete" | "failed"
	Progress      float64                `protobuf:"fixed64,8,opt,name=progress,proto3" json:"progress,omitempty"`
	Speed         string                 `protobuf:"bytes,9,opt,name=speed,proto3" json:"speed,omitempty"`
	Eta           string                 `protobuf:"bytes,10,opt,name=eta,proto3" json:"eta,omitempty"`
	FilePath      string                 `protobuf:"bytes,11,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadItem) Reset() {
	*x = DownloadItem{}
	mi := &file_backend_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadItem) ProtoMessage() {}

func (x *DownloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadItem.ProtoReflect.Descriptor instead.
func (*DownloadItem) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadItem) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *DownloadItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DownloadItem) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *DownloadItem) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *DownloadItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadItem) GetAudioOnly() bool {
	if x != nil {
		return x.AudioOnly
	}
	return false
}

func (x *DownloadItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadItem) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *DownloadItem) GetSpeed() string {
	if x != nil {
		return x.Speed
	}
	return ""
}

func (x *DownloadItem) GetEta() string {
	if x != nil {
		return x.Eta
	}
	return ""
}

func (x *DownloadItem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DownloadItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "download_progress" | "download_done" | "download_error"
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_backend_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_backend_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_backend_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_backend_v1_types_proto protoreflect.FileDescriptor

const file_backend_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x16backend/v1/types.proto\x12\n" +
	"backend.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"view_count\x18\x06 \x01(\x03R\tviewCount\x12\x1f\n" +
	"\vupload_date\x18\a \x01(\tR\n" +
	"uploadDate\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\xa6\x01\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12 \n" +
	"\vsubscribers\x18\x06 \x01(\x03R\vsubscribers\x12\x19\n" +
	"\bis_local\x18\a \x01(\bR\aisLocal\"\\\n" +
	"\n" +
	"RawChapter\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x01R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x01R\aendTime\"\xd4\x01\n" +
	"\fVideoDetails\x12'\n" +
	"\x05video\x18\x01 \x01(\v2\x11.backend.v1.VideoR\x05video\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rthumbnail_url\x18\x03 \x01(\tR\fthumbnailUrl\x12 \n" +
	"\vsubscribers\x18\x04 \x01(\x03R\vsubscribers\x122\n" +
	"\bchapters\x18\x05 \x03(\v2\x16.backend.v1.RawChapterR\bchapters\".\n" +
	"\x04Link\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\xb3\x01\n" +
	"\aChapter\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_start\x18\x02 \x01(\x01R\roriginalStart\x12!\n" +
	"\foriginal_end\x18\x03 \x01(\x01R\voriginalEnd\x12%\n" +
	"\x0eadjusted_start\x18\x04 \x01(\x01R\radjustedStart\x12!\n" +
	"\fadjusted_end\x18\x05 \x01(\x01R\vadjustedEnd\"3\n" +
	"\tSBSegment\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x01R\x03end\"\x83\x03\n" +
	"\rCachedDetails\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12#\n" +
	"\rthumbnail_url\x18\x02 \x01(\tR\fthumbnailUrl\x12 \n" +
	"\vsubscribers\x18\x03 \x01(\x03R\vsubscribers\x12&\n" +
	"\x05links\x18\x04 \x03(\v2\x10.backend.v1.LinkR\x05links\x12!\n" +
	"\flinks_parsed\x18\x05 \x01(\bR\vlinksParsed\x12/\n" +
	"\bchapters\x18\x06 \x03(\v2\x13.backend.v1.ChapterR\bchapters\x12'\n" +
	"\x0fchapters_parsed\x18\a \x01(\bR\x0echaptersParsed\x126\n" +
	"\vsb_segments\x18\b \x03(\v2\x15.backend.v1.SBSegmentR\n" +
	"sbSegments\x12,\n" +
	"\x12sb_segments_parsed\x18\t \x01(\bR\x10sbSegmentsParsed\"\xaa\x03\n" +
	"\n" +
	"LocalVideo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"view_count\x18\x05 \x01(\x03R\tviewCount\x12\x1f\n" +
	"\vupload_date\x18\x06 \x01(\tR\n" +
	"uploadDate\x12\x1b\n" +
	"\tfile_path\x18\a \x01(\tR\bfilePath\x12#\n" +
	"\rdownload_type\x18\b \x01(\tR\fdownloadType\x12?\n" +
	"\rdownloaded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fdownloadedAt\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12;\n" +
	"\vlast_played\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastPlayed\x12(\n" +
	"\x10last_position_ms\x18\f \x01(\x03R\x0elastPositionMs\"2\n" +
	"\n" +
	"YTPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"i\n" +
	"\bPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa5\x01\n" +
	"\x0fWatchLaterEntry\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x125\n" +
	"\badded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"\xd7\x02\n" +
	"\fHistoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x05 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"view_count\x18\a \x01(\x03R\tviewCount\x12\x1f\n" +
	"\vupload_date\x18\b \x01(\tR\n" +
	"uploadDate\x12\x1d\n" +
	"\n" +
	"event_type\x18\t \x01(\tR\teventType\x12\x18\n" +
	"\adetails\x18\n" +
	" \x01(\tR\adetails\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf8\x02\n" +
	"\rActivityEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\bis_local\x18\x03 \x01(\bR\aisLocal\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x05 \x01(\tR\vchannelName\x12\x1f\n" +
	"\vplaylist_id\x18\x06 \x01(\tR\n" +
	"playlistId\x12*\n" +
	"\x11playlist_local_id\x18\a \x01(\x03R\x0fplaylistLocalId\x12#\n" +
	"\rplaylist_name\x18\b \x01(\tR\fplaylistName\x12\x19\n" +
	"\bvideo_id\x18\t \x01(\tR\avideoId\x12\x1f\n" +
	"\vvideo_title\x18\n" +
	" \x01(\tR\n" +
	"videoTitle\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb5\x02\n" +
	"\fDownloadItem\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"audio_only\x18\x06 \x01(\bR\taudioOnly\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\b \x01(\x01R\bprogress\x12\x14\n" +
	"\x05speed\x18\t \x01(\tR\x05speed\x12\x10\n" +
	"\x03eta\x18\n" +
	" \x01(\tR\x03eta\x12\x1b\n" +
	"\tfile_path\x18\v \x01(\tR\bfilePath\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\"N\n" +
	"\x05Event\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detailBBZ@github.com/EugeneShtoka/yt-tui/internal/api/backend/v1;backendv1b\x06proto3"

var (
	file_backend_v1_types_proto_rawDescOnce sync.Once
	file_backend_v1_types_proto_rawDescData []byte
)

func file_backend_v1_types_proto_rawDescGZIP() []byte {
	file_backend_v1_types_proto_rawDescOnce.Do(func() {
		file_backend_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_v1_types_proto_rawDesc), len(file_backend_v1_types_proto_rawDesc)))
	})
	return file_backend_v1_types_proto_rawDescData
}

var file_backend_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_backend_v1_types_proto_goTypes = []any{
	(*Video)(nil),                 // 0: backend.v1.Video
	(*Channel)(nil),               // 1: backend.v1.Channel
	(*RawChapter)(nil),            // 2: backend.v1.RawChapter
	(*VideoDetails)(nil),          // 3: backend.v1.VideoDetails
	(*Link)(nil),                  // 4: backend.v1.Link
	(*Chapter)(nil),               // 5: backend.v1.Chapter
	(*SBSegment)(nil),             // 6: backend.v1.SBSegment
	(*CachedDetails)(nil),         // 7: backend.v1.CachedDetails
	(*LocalVideo)(nil),            // 8: backend.v1.LocalVideo
	(*YTPlaylist)(nil),            // 9: backend.v1.YTPlaylist
	(*Playlist)(nil),              // 10: backend.v1.Playlist
	(*WatchLaterEntry)(nil),       // 11: backend.v1.WatchLaterEntry
	(*HistoryEntry)(nil),          // 12: backend.v1.HistoryEntry
	(*ActivityEntry)(nil),         // 13: backend.v1.ActivityEntry
	(*DownloadItem)(nil),          // 14: backend.v1.DownloadItem
	(*Event)(nil),                 // 15: backend.v1.Event
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_backend_v1_types_proto_depIdxs = []int32{
	0,  // 0: backend.v1.VideoDetails.video:type_name -> backend.v1.Video
	2,  // 1: backend.v1.VideoDetails.chapters:type_name -> backend.v1.RawChapter
	4,  // 2: backend.v1.CachedDetails.links:type_name -> backend.v1.Link
	5,  // 3: backend.v1.CachedDetails.chapters:type_name -> backend.v1.Chapter
	6,  // 4: backend.v1.CachedDetails.sb_segments:type_name -> backend.v1.SBSegment
	16, // 5: backend.v1.LocalVideo.downloaded_at:type_name -> google.protobuf.Timestamp
	16, // 6: backend.v1.LocalVideo.last_played:type_name -> google.protobuf.Timestamp
	16, // 7: backend.v1.Playlist.created_at:type_name -> google.protobuf.Timestamp
	16, // 8: backend.v1.WatchLaterEntry.added_at:type_name -> google.protobuf.Timestamp
	16, // 9: backend.v1.HistoryEntry.timestamp:type_name -> google.protobuf.Timestamp
	16, // 10: backend.v1.ActivityEntry.timestamp:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_backend_v1_types_proto_init() }
func file_backend_v1_types_proto_init() {
	if File_backend_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_v1_types_proto_rawDesc), len(file_backend_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_v1_types_proto_goTypes,
		DependencyIndexes: file_backend_v1_types_proto_depIdxs,
		MessageInfos:      file_backend_v1_types_proto_msgTypes,
	}.Build()
	File_backend_v1_types_proto = out.File
	file_backend_v1_types_proto_goTypes = nil
	file_backend_v1_types_proto_depIdxs = nil
}
